name: location_mohammad_sharafi
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  freezed_annotation: ^2.0.1
  injectable: ^1.5.3
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.0
  socket_io_client: ^2.0.2
  flutter_map: ^5.0.0
  flutter_map_marker_cluster: ^1.2.0
  lottie: ^1.2.1
  mocktail: ^1.0.0
  flutter_bloc: ^8.1.1
  bloc_test: ^9.1.3
  auto_route: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed: ^2.3.4
  auto_route_generator: ^7.1.1
  injectable_generator: ^1.5.2
  device_info_plus: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - .env.prd
    - assets/lottie_files/
